### ISSUE TITLE
开发区校区校园网自动登录脚本(Python)

### ISSUE THREAD

**Issue by DawningW** [BeautyYuYanli/dlut-survival-tools#2]
窝来毛遂自荐一下(～￣▽￣)～
[https://github.com/DawningW/Python-Tests/tree/master/dlut](https://github.com/DawningW/Python-Tests/tree/master/dlut)
[Windows使用计划任务实现校园网全自动登录的教程](https://dawncraft.cc/2021/10/%E5%A4%A7%E5%B7%A5%E5%BC%80%E5%8F%91%E5%8C%BA%E6%A0%A1%E5%8C%BA%E6%A0%A1%E5%9B%AD%E7%BD%91%E8%87%AA%E5%8A%A8%E7%99%BB%E5%BD%95/)

**Comment by BeautyyuYanli** [comment]
Done!
