### ISSUE TITLE
图书馆约座小程序（另外一个）

### ISSUE THREAD

**Issue by qhy040404** [BeautyYuYanli/dlut-survival-tools#3]
[Library-reservation](https://github.com/qhy040404/DLUT-library-auto-reservation)

放在之前那个下面就行，毕竟最开始是用别人的框架改的，最近才彻底重写

废物毛遂自荐.jpg

**Comment by BeautyyuYanli** [comment]
哦哦前几天整忘了回复

你可以直接发个 pr 我合并上去

**Comment by qhy040404** [comment]
明天起床搞:smile:
